language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit -c phpunit.xml.dist
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar;
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml;
